/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lora.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "lora.pb-c.h"
void   main_valve_frame__init
                     (MainValveFrame         *message)
{
  static const MainValveFrame init_value = MAIN_VALVE_FRAME__INIT;
  *message = init_value;
}
size_t main_valve_frame__get_packed_size
                     (const MainValveFrame *message)
{
  assert(message->base.descriptor == &main_valve_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main_valve_frame__pack
                     (const MainValveFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main_valve_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main_valve_frame__pack_to_buffer
                     (const MainValveFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main_valve_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MainValveFrame *
       main_valve_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MainValveFrame *)
     protobuf_c_message_unpack (&main_valve_frame__descriptor,
                                allocator, len, data);
}
void   main_valve_frame__free_unpacked
                     (MainValveFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main_valve_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vent_valve_frame__init
                     (VentValveFrame         *message)
{
  static const VentValveFrame init_value = VENT_VALVE_FRAME__INIT;
  *message = init_value;
}
size_t vent_valve_frame__get_packed_size
                     (const VentValveFrame *message)
{
  assert(message->base.descriptor == &vent_valve_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vent_valve_frame__pack
                     (const VentValveFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vent_valve_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vent_valve_frame__pack_to_buffer
                     (const VentValveFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vent_valve_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VentValveFrame *
       vent_valve_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VentValveFrame *)
     protobuf_c_message_unpack (&vent_valve_frame__descriptor,
                                allocator, len, data);
}
void   vent_valve_frame__free_unpacked
                     (VentValveFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vent_valve_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lo_ra_frame__init
                     (LoRaFrame         *message)
{
  static const LoRaFrame init_value = LO_RA_FRAME__INIT;
  *message = init_value;
}
size_t lo_ra_frame__get_packed_size
                     (const LoRaFrame *message)
{
  assert(message->base.descriptor == &lo_ra_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lo_ra_frame__pack
                     (const LoRaFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lo_ra_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lo_ra_frame__pack_to_buffer
                     (const LoRaFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lo_ra_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoRaFrame *
       lo_ra_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoRaFrame *)
     protobuf_c_message_unpack (&lo_ra_frame__descriptor,
                                allocator, len, data);
}
void   lo_ra_frame__free_unpacked
                     (LoRaFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lo_ra_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor main_valve_frame__field_descriptors[3] =
{
  {
    "thermocuple1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MainValveFrame, thermocuple1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thermocuple2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MainValveFrame, thermocuple2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MainValveFrame, battery),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main_valve_frame__field_indices_by_name[] = {
  2,   /* field[2] = battery */
  0,   /* field[0] = thermocuple1 */
  1,   /* field[1] = thermocuple2 */
};
static const ProtobufCIntRange main_valve_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main_valve_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MainValveFrame",
  "MainValveFrame",
  "MainValveFrame",
  "",
  sizeof(MainValveFrame),
  3,
  main_valve_frame__field_descriptors,
  main_valve_frame__field_indices_by_name,
  1,  main_valve_frame__number_ranges,
  (ProtobufCMessageInit) main_valve_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vent_valve_frame__field_descriptors[4] =
{
  {
    "thermistor1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VentValveFrame, thermistor1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thermistor2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VentValveFrame, thermistor2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tankpressure",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VentValveFrame, tankpressure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batteryVoltage",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VentValveFrame, batteryvoltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vent_valve_frame__field_indices_by_name[] = {
  3,   /* field[3] = batteryVoltage */
  2,   /* field[2] = tankpressure */
  0,   /* field[0] = thermistor1 */
  1,   /* field[1] = thermistor2 */
};
static const ProtobufCIntRange vent_valve_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor vent_valve_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VentValveFrame",
  "VentValveFrame",
  "VentValveFrame",
  "",
  sizeof(VentValveFrame),
  4,
  vent_valve_frame__field_descriptors,
  vent_valve_frame__field_indices_by_name,
  1,  vent_valve_frame__number_ranges,
  (ProtobufCMessageInit) vent_valve_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lo_ra_frame__field_descriptors[4] =
{
  {
    "mainValve",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, mainvalve),
    &main_valve_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ventValve",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, ventvalve),
    &vent_valve_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lo_ra_frame__field_indices_by_name[] = {
  0,   /* field[0] = mainValve */
  3,   /* field[3] = state */
  2,   /* field[2] = uptime */
  1,   /* field[1] = ventValve */
};
static const ProtobufCIntRange lo_ra_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor lo_ra_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoRaFrame",
  "LoRaFrame",
  "LoRaFrame",
  "",
  sizeof(LoRaFrame),
  4,
  lo_ra_frame__field_descriptors,
  lo_ra_frame__field_indices_by_name,
  1,  lo_ra_frame__number_ranges,
  (ProtobufCMessageInit) lo_ra_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
