#ifndef BUZZER_CONFIG_H
#define BUZZER_CONFIG_H

#include <stddef.h>
#include "buzzer_pwm.h"

#define NOTE_C4 261
#define NOTE_D4 293
#define NOTE_E4 329
#define NOTE_F4 349
#define NOTE_G4 392
#define NOTE_A4 440
#define NOTE_A3 220
#define REST 0

#define BPM 98

#define QUARTER_NOTE (60000 / BPM)
#define WHOLE_NOTE (QUARTER_NOTE * 4)
#define HALF_NOTE (QUARTER_NOTE * 2)
#define HALF_NOTE_DOT (QUARTER_NOTE * 3)
#define SIXTEENTH_NOTE (QUARTER_NOTE / 4)
#define EIGHTH_NOTE (QUARTER_NOTE / 2)
#define EIGHTH_NOTE_DOT (SIXTEENTH_NOTE * 3)

typedef struct {
    uint16_t freq;
    uint16_t period;
} note_t;

static const note_t dlugosc_dzwieku_samotnosci[] = {
    {NOTE_C4, EIGHTH_NOTE},
    {NOTE_A4, EIGHTH_NOTE}, {NOTE_G4, EIGHTH_NOTE}, {NOTE_F4, EIGHTH_NOTE}, {NOTE_E4, EIGHTH_NOTE}, {NOTE_F4, EIGHTH_NOTE}, {NOTE_F4, EIGHTH_NOTE},{NOTE_F4, EIGHTH_NOTE},
    {NOTE_F4, EIGHTH_NOTE}, {NOTE_E4, HALF_NOTE_DOT}, {REST, QUARTER_NOTE}, {NOTE_F4, QUARTER_NOTE}, {NOTE_F4, SIXTEENTH_NOTE}, {NOTE_F4, EIGHTH_NOTE_DOT},
    {NOTE_F4, EIGHTH_NOTE}, {NOTE_E4, HALF_NOTE_DOT}, {REST, EIGHTH_NOTE}, {NOTE_E4, EIGHTH_NOTE}, {NOTE_E4, SIXTEENTH_NOTE}, {NOTE_F4, EIGHTH_NOTE_DOT},
    {NOTE_F4, EIGHTH_NOTE}, {NOTE_D4, HALF_NOTE_DOT}, {REST, QUARTER_NOTE}, {REST, EIGHTH_NOTE}, {NOTE_A3, EIGHTH_NOTE},
    {NOTE_A4, EIGHTH_NOTE}, {NOTE_G4, EIGHTH_NOTE}, {NOTE_F4, EIGHTH_NOTE}, {NOTE_E4, EIGHTH_NOTE}, {NOTE_F4, EIGHTH_NOTE}, {NOTE_F4, EIGHTH_NOTE}, {REST, EIGHTH_NOTE}, {NOTE_F4, EIGHTH_NOTE},
    {NOTE_F4, EIGHTH_NOTE}, {NOTE_E4, HALF_NOTE_DOT}, {REST, QUARTER_NOTE}, {NOTE_F4, SIXTEENTH_NOTE}, {NOTE_F4, EIGHTH_NOTE_DOT},
    {NOTE_F4, EIGHTH_NOTE}, {NOTE_E4, HALF_NOTE_DOT}, {REST, EIGHTH_NOTE}, {NOTE_E4, EIGHTH_NOTE}, {NOTE_E4, SIXTEENTH_NOTE}, {NOTE_F4, EIGHTH_NOTE_DOT},
    {NOTE_F4, EIGHTH_NOTE}, {NOTE_D4, HALF_NOTE_DOT}
};

bool buzzer_play_notes(const note_t *notes, size_t num_notes);

#endif
