#include <string.h>
#include "gen_pysd.h"

/**
 * @brief Get header size
 *
 * @param new_line_ending end string with new line character
 * @return size_t header size
 */
size_t pysd_get_header_size(bool new_line_ending) {
    size_t string_size;
    if (new_line_ending == true) {
        string_size = snprintf(NULL, 0, "error_esp_now;error_memory;error_mcb;error_sensors;error_recovery;error_last_exception;mcb state;mcb uptime;mcb flight_time;mcb disconnect_timer;mcb battery_voltage;mcb sensor_placeholder;mcb latitude;mcb longitude;mcb altitude;mcb satelites_in_view;mcb acc_x;mcb acc_y;mcb acc_z;mcb gyr_x;mcb gyr_y;mcb gyr_z;mcb mag_x;mcb mag_y;mcb mag_z;mcb temperature;mcb pressure;mcb altitude;mcb yaw;mcb pitch;mcb roll;vent_valve waken_up;vent_valve valve_state;vent_valve thermistor1;vent_valve thermistor2;vent_valve tank_pressure;vent_valve battery_voltage;main_valve waken_up;main_valve valve_state;main_valve thermocouple1;main_valve thermocouple2;main_valve battery_voltage;recovery isArmed;recovery isTeleActive;recovery easyMiniFirstStage;recovery easyMiniSecondStage;recovery telemetrumFirstStage;recovery telemetrumSecondStage;recovery firstStageDone;recovery secondStageDone;recovery firstStageContinouity;recovery secondStageContinouity;recovery separationSwitch1;recovery separationSwitch2;recovery pressure1;recovery pressure2;payload waken_up;payload vbat;tanwa tanWaState;tanwa pressureSensor;tanwa solenoid_fill;tanwa solenoid_depr;tanwa abortButton;tanwa igniterContinouity_1;tanwa igniterContinouity_2;tanwa hxRequest_RCK;tanwa hxRequest_TANK;tanwa vbat;tanwa motorState_1;tanwa motorState_2;tanwa motorState_3;tanwa motorState_4;tanwa rocketWeight_val;tanwa tankWeight_val;tanwa rocketWeightRaw_val;tanwa tankWeightRaw_val;tanwa interface_rck;tanwa interface_tank;tanwa interface_mcu;pitot wakenUp;pitot dynamic_press;pitot static_press;pitot temperature;pitot humid;pitot vbat;pitot speed;pitot alt;pitot pred_apogee;\n");
    } else {
        string_size = snprintf(NULL, 0, "error_esp_now;error_memory;error_mcb;error_sensors;error_recovery;error_last_exception;mcb state;mcb uptime;mcb flight_time;mcb disconnect_timer;mcb battery_voltage;mcb sensor_placeholder;mcb latitude;mcb longitude;mcb altitude;mcb satelites_in_view;mcb acc_x;mcb acc_y;mcb acc_z;mcb gyr_x;mcb gyr_y;mcb gyr_z;mcb mag_x;mcb mag_y;mcb mag_z;mcb temperature;mcb pressure;mcb altitude;mcb yaw;mcb pitch;mcb roll;vent_valve waken_up;vent_valve valve_state;vent_valve thermistor1;vent_valve thermistor2;vent_valve tank_pressure;vent_valve battery_voltage;main_valve waken_up;main_valve valve_state;main_valve thermocouple1;main_valve thermocouple2;main_valve battery_voltage;recovery isArmed;recovery isTeleActive;recovery easyMiniFirstStage;recovery easyMiniSecondStage;recovery telemetrumFirstStage;recovery telemetrumSecondStage;recovery firstStageDone;recovery secondStageDone;recovery firstStageContinouity;recovery secondStageContinouity;recovery separationSwitch1;recovery separationSwitch2;recovery pressure1;recovery pressure2;payload waken_up;payload vbat;tanwa tanWaState;tanwa pressureSensor;tanwa solenoid_fill;tanwa solenoid_depr;tanwa abortButton;tanwa igniterContinouity_1;tanwa igniterContinouity_2;tanwa hxRequest_RCK;tanwa hxRequest_TANK;tanwa vbat;tanwa motorState_1;tanwa motorState_2;tanwa motorState_3;tanwa motorState_4;tanwa rocketWeight_val;tanwa tankWeight_val;tanwa rocketWeightRaw_val;tanwa tankWeightRaw_val;tanwa interface_rck;tanwa interface_tank;tanwa interface_mcu;pitot wakenUp;pitot dynamic_press;pitot static_press;pitot temperature;pitot humid;pitot vbat;pitot speed;pitot alt;pitot pred_apogee;");
    }

    return string_size;
}

/**
 * @brief Get size of sd data frame
 *
 * @param pysd_main
 * @param new_line_ending end string with new line character
 * @return size_t frame size
 */
size_t pysd_get_sd_frame_size(rocket_data_t pysd_main, bool new_line_ending) {
    size_t string_size;
    if (new_line_ending == true) {
        string_size = snprintf(NULL, 0, "%lu;%lu;%lu;%lu;%lu;%lu;%d;%lu;%d;%lu;%f;%d;%f;%f;%f;%d;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%d;%d;%d;%d;%f;%f;%d;%d;%lu;%lu;%lu;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%lu;%lu;%lu;%lu;%d;%d;%d;%lu;%lu;%f;%lu;%lu;%lu;%lu;%f;%f;%lu;%lu;%d;%d;%d;%d;%f;%f;%f;%f;%f;%f;%f;%f;\n", pysd_main.error_esp_now, pysd_main.error_memory, pysd_main.error_mcb, pysd_main.error_sensors, pysd_main.error_recovery, pysd_main.error_last_exception, pysd_main.mcb.state, pysd_main.mcb.uptime, pysd_main.mcb.flight_time, pysd_main.mcb.disconnect_timer, pysd_main.mcb.battery_voltage, pysd_main.mcb.sensor_placeholder, pysd_main.mcb.latitude, pysd_main.mcb.longitude, pysd_main.mcb.altitude, pysd_main.mcb.satelites_in_view, pysd_main.mcb.acc_x, pysd_main.mcb.acc_y, pysd_main.mcb.acc_z, pysd_main.mcb.gyr_x, pysd_main.mcb.gyr_y, pysd_main.mcb.gyr_z, pysd_main.mcb.mag_x, pysd_main.mcb.mag_y, pysd_main.mcb.mag_z, pysd_main.mcb.temperature, pysd_main.mcb.pressure, pysd_main.mcb.altitude, pysd_main.mcb.yaw, pysd_main.mcb.pitch, pysd_main.mcb.roll, pysd_main.vent_valve.waken_up, pysd_main.vent_valve.valve_state, pysd_main.vent_valve.thermistor1, pysd_main.vent_valve.thermistor2, pysd_main.vent_valve.tank_pressure, pysd_main.vent_valve.battery_voltage, pysd_main.main_valve.waken_up, pysd_main.main_valve.valve_state, pysd_main.main_valve.thermocouple1, pysd_main.main_valve.thermocouple2, pysd_main.main_valve.battery_voltage, pysd_main.recovery.isArmed, pysd_main.recovery.isTeleActive, pysd_main.recovery.easyMiniFirstStage, pysd_main.recovery.easyMiniSecondStage, pysd_main.recovery.telemetrumFirstStage, pysd_main.recovery.telemetrumSecondStage, pysd_main.recovery.firstStageDone, pysd_main.recovery.secondStageDone, pysd_main.recovery.firstStageContinouity, pysd_main.recovery.secondStageContinouity, pysd_main.recovery.separationSwitch1, pysd_main.recovery.separationSwitch2, pysd_main.recovery.pressure1, pysd_main.recovery.pressure2, pysd_main.payload.waken_up, pysd_main.payload.vbat, pysd_main.tanwa.tanWaState, pysd_main.tanwa.pressureSensor, pysd_main.tanwa.solenoid_fill, pysd_main.tanwa.solenoid_depr, pysd_main.tanwa.abortButton, pysd_main.tanwa.igniterContinouity_1, pysd_main.tanwa.igniterContinouity_2, pysd_main.tanwa.hxRequest_RCK, pysd_main.tanwa.hxRequest_TANK, pysd_main.tanwa.vbat, pysd_main.tanwa.motorState_1, pysd_main.tanwa.motorState_2, pysd_main.tanwa.motorState_3, pysd_main.tanwa.motorState_4, pysd_main.tanwa.rocketWeight_val, pysd_main.tanwa.tankWeight_val, pysd_main.tanwa.rocketWeightRaw_val, pysd_main.tanwa.tankWeightRaw_val, pysd_main.tanwa.interface_rck, pysd_main.tanwa.interface_tank, pysd_main.tanwa.interface_mcu, pysd_main.pitot.wakenUp, pysd_main.pitot.dynamic_press, pysd_main.pitot.static_press, pysd_main.pitot.temperature, pysd_main.pitot.humid, pysd_main.pitot.vbat, pysd_main.pitot.speed, pysd_main.pitot.alt, pysd_main.pitot.pred_apogee);
    } else {
        string_size = snprintf(NULL, 0, "%lu;%lu;%lu;%lu;%lu;%lu;%d;%lu;%d;%lu;%f;%d;%f;%f;%f;%d;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%d;%d;%d;%d;%f;%f;%d;%d;%lu;%lu;%lu;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%lu;%lu;%lu;%lu;%d;%d;%d;%lu;%lu;%f;%lu;%lu;%lu;%lu;%f;%f;%lu;%lu;%d;%d;%d;%d;%f;%f;%f;%f;%f;%f;%f;%f;", pysd_main.error_esp_now, pysd_main.error_memory, pysd_main.error_mcb, pysd_main.error_sensors, pysd_main.error_recovery, pysd_main.error_last_exception, pysd_main.mcb.state, pysd_main.mcb.uptime, pysd_main.mcb.flight_time, pysd_main.mcb.disconnect_timer, pysd_main.mcb.battery_voltage, pysd_main.mcb.sensor_placeholder, pysd_main.mcb.latitude, pysd_main.mcb.longitude, pysd_main.mcb.altitude, pysd_main.mcb.satelites_in_view, pysd_main.mcb.acc_x, pysd_main.mcb.acc_y, pysd_main.mcb.acc_z, pysd_main.mcb.gyr_x, pysd_main.mcb.gyr_y, pysd_main.mcb.gyr_z, pysd_main.mcb.mag_x, pysd_main.mcb.mag_y, pysd_main.mcb.mag_z, pysd_main.mcb.temperature, pysd_main.mcb.pressure, pysd_main.mcb.altitude, pysd_main.mcb.yaw, pysd_main.mcb.pitch, pysd_main.mcb.roll, pysd_main.vent_valve.waken_up, pysd_main.vent_valve.valve_state, pysd_main.vent_valve.thermistor1, pysd_main.vent_valve.thermistor2, pysd_main.vent_valve.tank_pressure, pysd_main.vent_valve.battery_voltage, pysd_main.main_valve.waken_up, pysd_main.main_valve.valve_state, pysd_main.main_valve.thermocouple1, pysd_main.main_valve.thermocouple2, pysd_main.main_valve.battery_voltage, pysd_main.recovery.isArmed, pysd_main.recovery.isTeleActive, pysd_main.recovery.easyMiniFirstStage, pysd_main.recovery.easyMiniSecondStage, pysd_main.recovery.telemetrumFirstStage, pysd_main.recovery.telemetrumSecondStage, pysd_main.recovery.firstStageDone, pysd_main.recovery.secondStageDone, pysd_main.recovery.firstStageContinouity, pysd_main.recovery.secondStageContinouity, pysd_main.recovery.separationSwitch1, pysd_main.recovery.separationSwitch2, pysd_main.recovery.pressure1, pysd_main.recovery.pressure2, pysd_main.payload.waken_up, pysd_main.payload.vbat, pysd_main.tanwa.tanWaState, pysd_main.tanwa.pressureSensor, pysd_main.tanwa.solenoid_fill, pysd_main.tanwa.solenoid_depr, pysd_main.tanwa.abortButton, pysd_main.tanwa.igniterContinouity_1, pysd_main.tanwa.igniterContinouity_2, pysd_main.tanwa.hxRequest_RCK, pysd_main.tanwa.hxRequest_TANK, pysd_main.tanwa.vbat, pysd_main.tanwa.motorState_1, pysd_main.tanwa.motorState_2, pysd_main.tanwa.motorState_3, pysd_main.tanwa.motorState_4, pysd_main.tanwa.rocketWeight_val, pysd_main.tanwa.tankWeight_val, pysd_main.tanwa.rocketWeightRaw_val, pysd_main.tanwa.tankWeightRaw_val, pysd_main.tanwa.interface_rck, pysd_main.tanwa.interface_tank, pysd_main.tanwa.interface_mcu, pysd_main.pitot.wakenUp, pysd_main.pitot.dynamic_press, pysd_main.pitot.static_press, pysd_main.pitot.temperature, pysd_main.pitot.humid, pysd_main.pitot.vbat, pysd_main.pitot.speed, pysd_main.pitot.alt, pysd_main.pitot.pred_apogee);
    }

    return string_size;
}

/**
 * @brief Fill buffer with struct variables names
 * 
 * @param buffer pointer to buffer
 * @param size buffer size
 * @param rocket_data_t struct with data
 * @param new_line_ending end string with new line character
 * @return size_t size of wrote data, return 0 in case of failure
 */
size_t pysd_create_header(char *buffer, size_t size, bool new_line_ending) {
    size_t header_size = 0;

    if (new_line_ending == true) {
        header_size = snprintf(buffer, size, "error_esp_now;error_memory;error_mcb;error_sensors;error_recovery;error_last_exception;mcb state;mcb uptime;mcb flight_time;mcb disconnect_timer;mcb battery_voltage;mcb sensor_placeholder;mcb latitude;mcb longitude;mcb altitude;mcb satelites_in_view;mcb acc_x;mcb acc_y;mcb acc_z;mcb gyr_x;mcb gyr_y;mcb gyr_z;mcb mag_x;mcb mag_y;mcb mag_z;mcb temperature;mcb pressure;mcb altitude;mcb yaw;mcb pitch;mcb roll;vent_valve waken_up;vent_valve valve_state;vent_valve thermistor1;vent_valve thermistor2;vent_valve tank_pressure;vent_valve battery_voltage;main_valve waken_up;main_valve valve_state;main_valve thermocouple1;main_valve thermocouple2;main_valve battery_voltage;recovery isArmed;recovery isTeleActive;recovery easyMiniFirstStage;recovery easyMiniSecondStage;recovery telemetrumFirstStage;recovery telemetrumSecondStage;recovery firstStageDone;recovery secondStageDone;recovery firstStageContinouity;recovery secondStageContinouity;recovery separationSwitch1;recovery separationSwitch2;recovery pressure1;recovery pressure2;payload waken_up;payload vbat;tanwa tanWaState;tanwa pressureSensor;tanwa solenoid_fill;tanwa solenoid_depr;tanwa abortButton;tanwa igniterContinouity_1;tanwa igniterContinouity_2;tanwa hxRequest_RCK;tanwa hxRequest_TANK;tanwa vbat;tanwa motorState_1;tanwa motorState_2;tanwa motorState_3;tanwa motorState_4;tanwa rocketWeight_val;tanwa tankWeight_val;tanwa rocketWeightRaw_val;tanwa tankWeightRaw_val;tanwa interface_rck;tanwa interface_tank;tanwa interface_mcu;pitot wakenUp;pitot dynamic_press;pitot static_press;pitot temperature;pitot humid;pitot vbat;pitot speed;pitot alt;pitot pred_apogee;\n");
    } else {
        header_size = snprintf(buffer, size, "error_esp_now;error_memory;error_mcb;error_sensors;error_recovery;error_last_exception;mcb state;mcb uptime;mcb flight_time;mcb disconnect_timer;mcb battery_voltage;mcb sensor_placeholder;mcb latitude;mcb longitude;mcb altitude;mcb satelites_in_view;mcb acc_x;mcb acc_y;mcb acc_z;mcb gyr_x;mcb gyr_y;mcb gyr_z;mcb mag_x;mcb mag_y;mcb mag_z;mcb temperature;mcb pressure;mcb altitude;mcb yaw;mcb pitch;mcb roll;vent_valve waken_up;vent_valve valve_state;vent_valve thermistor1;vent_valve thermistor2;vent_valve tank_pressure;vent_valve battery_voltage;main_valve waken_up;main_valve valve_state;main_valve thermocouple1;main_valve thermocouple2;main_valve battery_voltage;recovery isArmed;recovery isTeleActive;recovery easyMiniFirstStage;recovery easyMiniSecondStage;recovery telemetrumFirstStage;recovery telemetrumSecondStage;recovery firstStageDone;recovery secondStageDone;recovery firstStageContinouity;recovery secondStageContinouity;recovery separationSwitch1;recovery separationSwitch2;recovery pressure1;recovery pressure2;payload waken_up;payload vbat;tanwa tanWaState;tanwa pressureSensor;tanwa solenoid_fill;tanwa solenoid_depr;tanwa abortButton;tanwa igniterContinouity_1;tanwa igniterContinouity_2;tanwa hxRequest_RCK;tanwa hxRequest_TANK;tanwa vbat;tanwa motorState_1;tanwa motorState_2;tanwa motorState_3;tanwa motorState_4;tanwa rocketWeight_val;tanwa tankWeight_val;tanwa rocketWeightRaw_val;tanwa tankWeightRaw_val;tanwa interface_rck;tanwa interface_tank;tanwa interface_mcu;pitot wakenUp;pitot dynamic_press;pitot static_press;pitot temperature;pitot humid;pitot vbat;pitot speed;pitot alt;pitot pred_apogee;");
    }

    return header_size;
}

/**
 * @brief Fill buffer with struct data
 *
 * @param buffer pointer to buffer
 * @param size buffer size
 * @param ...pysd_main... struct with data
 * @param new_line_ending end string with new line character
 * @return size_t size of wrote data, return 0 in case of failure
 */
size_t pysd_create_sd_frame(char *buffer, size_t size, rocket_data_t pysd_main, bool new_line_ending) {
    size_t frame_size = 0 ;

    if (new_line_ending == true) {
        frame_size = snprintf(buffer, size, "%lu;%lu;%lu;%lu;%lu;%lu;%d;%lu;%d;%lu;%f;%d;%f;%f;%f;%d;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%d;%d;%d;%d;%f;%f;%d;%d;%lu;%lu;%lu;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%lu;%lu;%lu;%lu;%d;%d;%d;%lu;%lu;%f;%lu;%lu;%lu;%lu;%f;%f;%lu;%lu;%d;%d;%d;%d;%f;%f;%f;%f;%f;%f;%f;%f;\n", pysd_main.error_esp_now, pysd_main.error_memory, pysd_main.error_mcb, pysd_main.error_sensors, pysd_main.error_recovery, pysd_main.error_last_exception, pysd_main.mcb.state, pysd_main.mcb.uptime, pysd_main.mcb.flight_time, pysd_main.mcb.disconnect_timer, pysd_main.mcb.battery_voltage, pysd_main.mcb.sensor_placeholder, pysd_main.mcb.latitude, pysd_main.mcb.longitude, pysd_main.mcb.altitude, pysd_main.mcb.satelites_in_view, pysd_main.mcb.acc_x, pysd_main.mcb.acc_y, pysd_main.mcb.acc_z, pysd_main.mcb.gyr_x, pysd_main.mcb.gyr_y, pysd_main.mcb.gyr_z, pysd_main.mcb.mag_x, pysd_main.mcb.mag_y, pysd_main.mcb.mag_z, pysd_main.mcb.temperature, pysd_main.mcb.pressure, pysd_main.mcb.altitude, pysd_main.mcb.yaw, pysd_main.mcb.pitch, pysd_main.mcb.roll, pysd_main.vent_valve.waken_up, pysd_main.vent_valve.valve_state, pysd_main.vent_valve.thermistor1, pysd_main.vent_valve.thermistor2, pysd_main.vent_valve.tank_pressure, pysd_main.vent_valve.battery_voltage, pysd_main.main_valve.waken_up, pysd_main.main_valve.valve_state, pysd_main.main_valve.thermocouple1, pysd_main.main_valve.thermocouple2, pysd_main.main_valve.battery_voltage, pysd_main.recovery.isArmed, pysd_main.recovery.isTeleActive, pysd_main.recovery.easyMiniFirstStage, pysd_main.recovery.easyMiniSecondStage, pysd_main.recovery.telemetrumFirstStage, pysd_main.recovery.telemetrumSecondStage, pysd_main.recovery.firstStageDone, pysd_main.recovery.secondStageDone, pysd_main.recovery.firstStageContinouity, pysd_main.recovery.secondStageContinouity, pysd_main.recovery.separationSwitch1, pysd_main.recovery.separationSwitch2, pysd_main.recovery.pressure1, pysd_main.recovery.pressure2, pysd_main.payload.waken_up, pysd_main.payload.vbat, pysd_main.tanwa.tanWaState, pysd_main.tanwa.pressureSensor, pysd_main.tanwa.solenoid_fill, pysd_main.tanwa.solenoid_depr, pysd_main.tanwa.abortButton, pysd_main.tanwa.igniterContinouity_1, pysd_main.tanwa.igniterContinouity_2, pysd_main.tanwa.hxRequest_RCK, pysd_main.tanwa.hxRequest_TANK, pysd_main.tanwa.vbat, pysd_main.tanwa.motorState_1, pysd_main.tanwa.motorState_2, pysd_main.tanwa.motorState_3, pysd_main.tanwa.motorState_4, pysd_main.tanwa.rocketWeight_val, pysd_main.tanwa.tankWeight_val, pysd_main.tanwa.rocketWeightRaw_val, pysd_main.tanwa.tankWeightRaw_val, pysd_main.tanwa.interface_rck, pysd_main.tanwa.interface_tank, pysd_main.tanwa.interface_mcu, pysd_main.pitot.wakenUp, pysd_main.pitot.dynamic_press, pysd_main.pitot.static_press, pysd_main.pitot.temperature, pysd_main.pitot.humid, pysd_main.pitot.vbat, pysd_main.pitot.speed, pysd_main.pitot.alt, pysd_main.pitot.pred_apogee);
    } else {
        frame_size = snprintf(buffer, size, "%lu;%lu;%lu;%lu;%lu;%lu;%d;%lu;%d;%lu;%f;%d;%f;%f;%f;%d;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%f;%d;%d;%d;%d;%f;%f;%d;%d;%lu;%lu;%lu;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%lu;%lu;%lu;%lu;%d;%d;%d;%lu;%lu;%f;%lu;%lu;%lu;%lu;%f;%f;%lu;%lu;%d;%d;%d;%d;%f;%f;%f;%f;%f;%f;%f;%f;", pysd_main.error_esp_now, pysd_main.error_memory, pysd_main.error_mcb, pysd_main.error_sensors, pysd_main.error_recovery, pysd_main.error_last_exception, pysd_main.mcb.state, pysd_main.mcb.uptime, pysd_main.mcb.flight_time, pysd_main.mcb.disconnect_timer, pysd_main.mcb.battery_voltage, pysd_main.mcb.sensor_placeholder, pysd_main.mcb.latitude, pysd_main.mcb.longitude, pysd_main.mcb.altitude, pysd_main.mcb.satelites_in_view, pysd_main.mcb.acc_x, pysd_main.mcb.acc_y, pysd_main.mcb.acc_z, pysd_main.mcb.gyr_x, pysd_main.mcb.gyr_y, pysd_main.mcb.gyr_z, pysd_main.mcb.mag_x, pysd_main.mcb.mag_y, pysd_main.mcb.mag_z, pysd_main.mcb.temperature, pysd_main.mcb.pressure, pysd_main.mcb.altitude, pysd_main.mcb.yaw, pysd_main.mcb.pitch, pysd_main.mcb.roll, pysd_main.vent_valve.waken_up, pysd_main.vent_valve.valve_state, pysd_main.vent_valve.thermistor1, pysd_main.vent_valve.thermistor2, pysd_main.vent_valve.tank_pressure, pysd_main.vent_valve.battery_voltage, pysd_main.main_valve.waken_up, pysd_main.main_valve.valve_state, pysd_main.main_valve.thermocouple1, pysd_main.main_valve.thermocouple2, pysd_main.main_valve.battery_voltage, pysd_main.recovery.isArmed, pysd_main.recovery.isTeleActive, pysd_main.recovery.easyMiniFirstStage, pysd_main.recovery.easyMiniSecondStage, pysd_main.recovery.telemetrumFirstStage, pysd_main.recovery.telemetrumSecondStage, pysd_main.recovery.firstStageDone, pysd_main.recovery.secondStageDone, pysd_main.recovery.firstStageContinouity, pysd_main.recovery.secondStageContinouity, pysd_main.recovery.separationSwitch1, pysd_main.recovery.separationSwitch2, pysd_main.recovery.pressure1, pysd_main.recovery.pressure2, pysd_main.payload.waken_up, pysd_main.payload.vbat, pysd_main.tanwa.tanWaState, pysd_main.tanwa.pressureSensor, pysd_main.tanwa.solenoid_fill, pysd_main.tanwa.solenoid_depr, pysd_main.tanwa.abortButton, pysd_main.tanwa.igniterContinouity_1, pysd_main.tanwa.igniterContinouity_2, pysd_main.tanwa.hxRequest_RCK, pysd_main.tanwa.hxRequest_TANK, pysd_main.tanwa.vbat, pysd_main.tanwa.motorState_1, pysd_main.tanwa.motorState_2, pysd_main.tanwa.motorState_3, pysd_main.tanwa.motorState_4, pysd_main.tanwa.rocketWeight_val, pysd_main.tanwa.tankWeight_val, pysd_main.tanwa.rocketWeightRaw_val, pysd_main.tanwa.tankWeightRaw_val, pysd_main.tanwa.interface_rck, pysd_main.tanwa.interface_tank, pysd_main.tanwa.interface_mcu, pysd_main.pitot.wakenUp, pysd_main.pitot.dynamic_press, pysd_main.pitot.static_press, pysd_main.pitot.temperature, pysd_main.pitot.humid, pysd_main.pitot.vbat, pysd_main.pitot.speed, pysd_main.pitot.alt, pysd_main.pitot.pred_apogee);
    }

    return frame_size;
}